## DictVectorizer 方法解释    
DictVectorizer 是 scikit-learn 中的一个实用工具，用于将字典形式的数据转换为机器学习模型可处理的特征矩阵。主要用于处理包含字符串或分类特征的字典数据，将其转换为数值型的稀疏矩阵或密集矩阵。

## 核心方法与参数
1. fit(X, y=None)
 * 作用：从训练数据中学习特征名称和对应索引
 * 参数：
    - X：字典列表，每个字典表示一个样本
    - y：可选参数，通常忽略
2. transform(X)
 * 作用：将字典数据转换为特征矩阵
 * 返回：
    - 稀疏矩阵（默认）或密集矩阵（当 sparse=False 时）
3. fit_transform(X, y=None)
 * 作用：合并 fit 和 transform 操作，更高效
4. get_feature_names_out()
 * 作用：返回转换后的特征名称列表
5. 主要参数：
 * sparse=True：是否返回稀疏矩阵
 * dtype=np.float64：输出矩阵的数据类型
 * separator='='：字符串特征的分隔符

## 样例代码    
以下是一个完整的示例，展示如何使用 DictVectorizer 处理包含分类和数值特征的字典数据：

In [1]:
from sklearn.feature_extraction import DictVectorizer
import numpy as np

# 示例数据：用户信息字典列表
data = [
    {'city': '北京', 'temperature': 22, 'humidity': 'high'},
    {'city': '上海', 'temperature': 28, 'humidity': 'medium'},
    {'city': '广州', 'temperature': 30, 'humidity': 'high'},
    {'city': '北京', 'temperature': 18, 'humidity': 'low'}
]

# 创建 DictVectorizer 实例
vectorizer = DictVectorizer(sparse=False)

# 拟合数据并转换
X = vectorizer.fit_transform(data)

# 查看特征名称
feature_names = vectorizer.get_feature_names_out()
print("特征名称:", feature_names)

# 查看转换后的特征矩阵
print("\n特征矩阵:\n", X)

# 转换单个新样本
new_sample = {'city': '上海', 'temperature': 25, 'humidity': 'low'}
new_X = vectorizer.transform([new_sample])
print("\n新样本转换结果:\n", new_X)

# 反向转换：从特征矩阵还原为字典
reverse_transformed = vectorizer.inverse_transform(X)
print("\n反向转换结果:\n", reverse_transformed)

特征名称: ['city=上海' 'city=北京' 'city=广州' 'humidity=high' 'humidity=low'
 'humidity=medium' 'temperature']

特征矩阵:
 [[ 0.  1.  0.  1.  0.  0. 22.]
 [ 1.  0.  0.  0.  0.  1. 28.]
 [ 0.  0.  1.  1.  0.  0. 30.]
 [ 0.  1.  0.  0.  1.  0. 18.]]

新样本转换结果:
 [[ 1.  0.  0.  0.  1.  0. 25.]]

反向转换结果:
 [{'city=北京': np.float64(1.0), 'humidity=high': np.float64(1.0), 'temperature': np.float64(22.0)}, {'city=上海': np.float64(1.0), 'humidity=medium': np.float64(1.0), 'temperature': np.float64(28.0)}, {'city=广州': np.float64(1.0), 'humidity=high': np.float64(1.0), 'temperature': np.float64(30.0)}, {'city=北京': np.float64(1.0), 'humidity=low': np.float64(1.0), 'temperature': np.float64(18.0)}]


## 应用场景
 * 自然语言处理：处理文本特征
 * 数据预处理：将非结构化数据转换为模型可接受的格式
 * 特征工程：快速生成特征矩阵，支持后续机器学习算法